version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/shopify-app-metaobjects
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 4000
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 4000
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ubuntu
