# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Content editor"
client_id = "5f686c12d364e170d30bac13d125e683"
application_url = "https://campaigns-exclusive-wooden-letting.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobject_definitions,write_metaobjects,read_metaobjects"

[auth]
redirect_urls = [
  "https://campaigns-exclusive-wooden-letting.trycloudflare.com/auth/callback",
  "https://campaigns-exclusive-wooden-letting.trycloudflare.com/auth/shopify/callback",
  "https://campaigns-exclusive-wooden-letting.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "oves-2022-test.myshopify.com"
