# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "content-editor"
client_id = "711155bca565a06b2e097bbe1198c624"
application_url = "https://edward-parental-prince-vessel.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobject_definitions,write_metaobjects,read_metaobjects"

[auth]
redirect_urls = [
  "https://edward-parental-prince-vessel.trycloudflare.com/auth/callback",
  "https://edward-parental-prince-vessel.trycloudflare.com/auth/shopify/callback",
  "https://edward-parental-prince-vessel.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-omnivoltaic.myshopify.com"
